package com.pismo.dynamodb.entity;

import java.time.LocalDateTime;
import java.util.UUID;

import com.pismo.dynamodb.entity.LocalDateTimeConverter;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Setter;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@DynamoDBDocument
public class AccountId {
    private String id;
    private String sk;
    // private LocalDateTime eventDate;

    @DynamoDBHashKey(attributeName = "id")
    public String getId() {
        return id;
    }

    @DynamoDBRangeKey(attributeName = "sk")
    public String getSk() {
        return sk;
    }
    
    // @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    // @DynamoDBAttribute
    // public LocalDateTime getEventDate() {
    //     return eventDate;
    // }

    public AccountId(String sk) { //, LocalDateTime now
        this.sk = sk;
        this.id = UUID.randomUUID().toString();
        // this.eventDate = now;
    }
}
