package com.pismo.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "pismo-account")
public class Account {

    private String id;
    private String sk;
    private String documentNumber;
    private String amount;
    private String eventDate;
    private String description;

    public Account() {
    }

    public Account(String documentNumber, String sk) {
        this.sk = sk;
        this.documentNumber = documentNumber;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }

    @DynamoDBAttribute
    public String getSK() {
        return this.sk;
    }

    @DynamoDBAttribute
    public String getDocumentNumber() {
        return this.documentNumber;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setSK(String sk) {
        this.sk = sk;
    }

    public void setDocumentNumber(String cost) {
        this.documentNumber = cost;
    }

}
