package com.baeldung.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "pismo-account")
public class Account {

    private String account_id;
    private String sk;
    private String cost;

    public Account() {
    }

    public Account(String cost, String msrp) {
        this.sk = msrp;
        this.cost = cost;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return account_id;
    }

    @DynamoDBAttribute
    public String getSK() {
        return sk;
    }

    @DynamoDBAttribute
    public String getCost() {
        return cost;
    }

    public void setId(String id) {
        this.account_id = id;
    }

    public void setSK(String msrp) {
        this.sk = msrp;
    }

    public void setCost(String cost) {
        this.cost = cost;
    }

}
