package com.pimso.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "pismo-account")
public class Account {

    private String account_id;
    private String sk;
    private String document_number;

    public Account() {
    }

    public Account(String documentNumber, String sk) {
        this.sk = sk;
        this.document_number = documentNumber;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return account_id;
    }

    @DynamoDBAttribute
    public String getSK() {
        return sk;
    }

    @DynamoDBAttribute
    public String getDocumentNumber() {
        return document_number;
    }

    public void setId(String id) {
        this.account_id = id;
    }

    public void setSK(String sk) {
        this.sk = sk;
    }

    public void setDocumentNumber(String cost) {
        this.document_number = cost;
    }

}
